name: "Philips Air MQTT"
description: "Control Philips air purifier via MQTT using py-air-control"
version: "1.0.0"
slug: "philips_air_mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
